# Lecture 5: More Pythony Goodness

In [1]:
a = [1,2,3]
b = [4,5,6]
c = a+b
print(c)

[1, 2, 3, 4, 5, 6]


In [98]:
g = [5]

In [99]:
print(g)

[5]


You can see, adding two lists just results in a longer list, catenation of the two.


In [2]:
print(a)
print(b)
a.append(b)
print(a)

[1, 2, 3]
[4, 5, 6]
[1, 2, 3, [4, 5, 6]]


In [9]:
def mysum(data):
    """ 
    Sum the elements of an array
    """
    asum = 0.0
    for i in data:
        asum = asum + i
    return asum

def mysum2(data):
    """ 
    Sum the elements of an array
    """
    asum = 0.0
    for i in range(data):
        asum = asum + i
    return asum

In [10]:
print(mysum([5,10,15]))
print(mysum2(5))

30.0
10.0


In [28]:
# the length of the array is defined here, and re-used below
# to test performance, we can make this number very large 
# 1000, 1000000 etc.

n = pow(10, 2)

In [31]:
%%time
a = list(range(n))

print(a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
CPU times: user 0 ns, sys: 4 ms, total: 4 ms
Wall time: 1.75 ms


In [20]:
%%time
print(sum(a))

4999950000.0
CPU times: user 20 ms, sys: 0 ns, total: 20 ms
Wall time: 19.5 ms


In [23]:
import numpy as np

np.array(4)

array(4)

In [45]:
%%time
a=np.arange(n)

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]
CPU times: user 4 ms, sys: 0 ns, total: 4 ms
Wall time: 1.52 ms


In [42]:
%%time
print(sum(a))

4950.0
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 922 µs


In [46]:
#%%time
%time print(a.sum())
%time print(a.sum())

a = np.arange(1.e6)
%time print(a.sum())

4950
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 276 µs
4950
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 168 µs
499999500000.0
CPU times: user 0 ns, sys: 0 ns, total: 0 ns
Wall time: 1.42 ms


In [49]:
a=np.arange(10)
b=np.arange(10)
c = a + b
d = 3*a*a + b + 2.0
print(c)
print(d)

[ 0  2  4  6  8 10 12 14 16 18]
[   2.    6.   16.   32.   54.   82.  116.  156.  202.  254.]


In [55]:
a = np.array([2, 5, 7])
b = np.array([2, 4, 7])
print(a,b)

print(3 *a)

[2 5 7] [2 4 7]
[ 6 15 21]


In [57]:
cc.shape

(10,)

In [70]:
c = np.arange(10)

c2=c.reshape(5,2)
c3=np.array(c.reshape(5,2))

In [71]:
print("c", c)
print("c2", c2)
print("c3", c3)
type(c)

c [0 1 2 3 4 5 6 7 8 9]
c2 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
c3 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


numpy.ndarray

In [72]:
c[0]=999

In [76]:
print(c)
print(c2)
print(c3)

[999   1   2   3   4   5   6   7   8   9]
[[999   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8   9]]
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [96]:
d2=c.reshape(5,2)[:][0,1:2]
print(d2)

[1]


In [ ]:
d2[1,1]=888

In [ ]:
print(c)

In [ ]:
print(c2)

Finally, this notebook can also be saved in python, and run through ipython (*or python if no cell_magic was used*). Try this out!

Notice the difference in running it via
```
    python 03-arrays.py
```
and
```
    ipython 03-arrays.py
```
